### ISSUE TITLE
H2 instead of Sqlite or an ORM

### ISSUE THREAD

**Issue by disconsented** [WaikatoUniMM2017/COMP315#2]
Ive been looking into our database options some more and found out a few important things.
Hibernate (The Java ORM library I was talking about) has poor sqlite support for the current version, android is a little special because google wrote a driver for it effectively. It also requires extra software to be installed on the machine that will be running the software (which Ill now refer to as the server).

As an alternative I've found [H2](http://www.h2database.com/html/main.html) the important things to take away from this is that we can embed it (no extra software needs to be installed on the client), it supports multi user writes (so much less work getting it working correctly) and it supports using the Postgresql driver so that gives us an option to move it across later if we wish to.

Thoughts? @FromSkyrim @CPinto1995

**Comment by FromSkyrim** [comment]
Sounds like H2 is a better choice embed it into the java program is , it just I haven't use it before so I will look into it, shouldn't be a problem.

**Comment by disconsented** [comment]
I don't have any experience with H2 either, should be interesting to see how this goes

On 1 Aug 2017 3:52 pm, Jiaming Zhang <notifications@github.com> wrote:

Sounds like H2 is a better choice embed it into the java program is , it just I haven't use it before so I will look into it, shouldn't be a problem.

**Comment by disconsented** [comment]
Well I think this is pretty much decided; failing any issues we will go with this
