### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by disconsented** [WaikatoUniMM2017/COMP315#3]
We need to start planning out how we will handle the web server side of things, I am not particularly experienced with the Java side of this (recently have been using Iron and Diesel with the Rust language for this)

I've stumbled across [this](https://www.ibm.com/developerworks/library/wa-aj-tomcat/) I think its a good start, the biggest concern that I can think of for the moment is how we will transmit the data (in particular the rounds). JSON should work well for us in that regard.

**Comment by FromSkyrim** [comment]
I think JSON will be good.

**Comment by disconsented** [comment]
After talking with @BaTmAnOmOrE if we don't find anything better we will probably end up using Apache Tomcat for this
