### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by FromSkyrim** [WaikatoUniMM2017/COMP315#4]
Use Case Diagram for WUGS Project.
![use case diagram for wugs project](https://user-images.githubusercontent.com/12493704/29167133-55fd0366-7e1d-11e7-8779-2f960b3aff7c.png)

First UI Sketch
![ui sketch](https://user-images.githubusercontent.com/12493704/29167147-5f0c9584-7e1d-11e7-850c-b618f1d0b9e0.png)

**Comment by disconsented** [comment]
https://docs.google.com/drawings/d/158C93DW4833T23RxuW26MIKv51jObkZj84nz03k_g-s/edit?usp=sharing

My take on the Use Case diagram
