### ISSUE TITLE
Prelim UI design

### ISSUE THREAD

**Issue by disconsented** [WaikatoUniMM2017/COMP315#6]
The big thing we want here is the tournament brackets, if possible try and get it working with dOT

**Comment by disconsented** [comment]
We need to include the WUGS logo somewhere in the UI, I can grab the assets if needed but I think it's better that Callan gets what he needs directly from Tom

**Comment by BaTmAnOmOrE** [comment]
I've already have all the images before hand. Just a matter or deciding
which logo to use.
